/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetografico01;

import javax.swing.JOptionPane;

/**
 *
 * @author luis
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        rbtmasculino = new javax.swing.JRadioButton();
        rbtfeminino = new javax.swing.JRadioButton();
        jButtonconfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMusica = new javax.swing.JLabel();
        ckbMpb = new javax.swing.JCheckBox();
        ckbRock = new javax.swing.JCheckBox();
        ckbSertanejo = new javax.swing.JCheckBox();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(60, 104, 84));

        buttonGroup1.add(rbtmasculino);
        rbtmasculino.setText("Masculino");

        buttonGroup1.add(rbtfeminino);
        rbtfeminino.setText("Feminino");

        jButtonconfirmar.setBackground(new java.awt.Color(60, 218, 198));
        jButtonconfirmar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonconfirmar.setText("Confirmar");
        jButtonconfirmar.setToolTipText("");
        jButtonconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonconfirmarActionPerformed(evt);
            }
        });

        jLabel1.setText("Sexo selecionado:");

        jLabel2.setText("Sexo:");

        lblSexo.setText("Nenhum");

        jLabel4.setText("Estilo Musical:");

        jLabel5.setText("Estilo selecionado:");

        lblMusica.setText("Nenhum");

        ckbMpb.setText("MPB");

        ckbRock.setText("Rock");

        ckbSertanejo.setText("Sertanejo");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MG", "SP", "PA", "BA", "AC" }));

        jLabel3.setText("Estado:");

        lblEstado.setText("Nenhum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(29, 29, 29)
                                .addComponent(lblMusica))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSexo)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(rbtmasculino)
                            .addComponent(rbtfeminino)
                            .addComponent(ckbSertanejo)
                            .addComponent(ckbMpb)
                            .addComponent(ckbRock))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(lblEstado))
                                .addContainerGap(93, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonconfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtmasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtfeminino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonconfirmar)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSexo))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEstado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckbMpb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckbRock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckbSertanejo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblMusica))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void selecionaSexo(){
        //isSelect representa o que está selecionado
        if(rbtfeminino.isSelected()){
        lblSexo.setText(rbtfeminino.getText());
        }
        else if(rbtmasculino.isSelected()){
            lblSexo.setText(rbtmasculino.getText());
        }
        else{
            JOptionPane.showMessageDialog(null,"Selecione o sexo",
                    "Sexo não selecionado", JOptionPane.QUESTION_MESSAGE);
        }
    }
    
    private void selecionaMusica(){
        String musica = " ";
        // o + na frente do código representa que pode ter mais de uma opção marcada
        
        if(ckbRock.isSelected()){
        musica += ckbRock.getText() + " ";
        //musica + ou + ckbRock como texto + "Alguma tipo de musica caso seja selecionado"
        }
        if(ckbMpb.isSelected()){
        musica += ckbMpb.getText() + " ";
        }
        if(ckbSertanejo.isSelected()){
        musica += ckbSertanejo.getText() + " ";
        }
        lblMusica.setText(musica);
        
    }
    
    private void estado(){
        if(cbxEstado.getSelectedIndex() == 0){
        String uf = cbxEstado.getSelectedItem().toString();
        lblEstado.setText(uf);
        }
        if(cbxEstado.getSelectedIndex() == 1){
        String uf = cbxEstado.getSelectedItem().toString();
        lblEstado.setText(uf);
        }
    }
    
    private void jButtonconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonconfirmarActionPerformed
        // TODO add your handling code here:
        selecionaSexo();
        selecionaMusica();
        estado();
    }//GEN-LAST:event_jButtonconfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JCheckBox ckbMpb;
    private javax.swing.JCheckBox ckbRock;
    private javax.swing.JCheckBox ckbSertanejo;
    private javax.swing.JButton jButtonconfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblMusica;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JRadioButton rbtfeminino;
    private javax.swing.JRadioButton rbtmasculino;
    // End of variables declaration//GEN-END:variables
}
