/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadorasimples;

import java.awt.event.KeyListener;
import java.awt.event.KeyEvent;

/**
 *
 * @author luis
 */
public class InterfaceSimples extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceSimples
     */
    //linha construtora da classe InterfaceSimples
    public InterfaceSimples() {
        //O método initComponents() é fornecido pela classe JFrame e é usado 
        //para inicializar a interface gráfica do usuário.
        initComponents();
        //O listener de evento é chamado quando o usuário pressiona uma tecla.
        jnum1.addKeyListener (new KeyListener(){
        @Override
         //O modificador override é usado para indicar que um método está sobrescrevendo um método
         //de uma superclasse.
         //Quando uma classe herda de outra classe, ela pode sobrescrever os métodos da superclasse.
         //A sobrescrita de métodos permite que uma classe subclasse implemente sua própria lógica
         //para um método herdado.
            public void keyTyped(KeyEvent e) {
           }
    
           @Override
           //Esses métodos são chamados quando o usuário digita uma tecla ou pressiona uma tecla
            public void keyPressed(KeyEvent e) {

                // Verificar se a tecla pressionada foi a tecla Enter
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {

                    // Transferir o foco para o campo de texto jnum2
                    jnum2.requestFocus();
                }
            }
        @Override
        // O método keyReleased() é chamado quando o usuário solta uma tecla.
             public void keyReleased(KeyEvent e) {
                 
            }
        });
    }

    

    
    double num1, num2, resultado;
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnum1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jnum1 = new javax.swing.JTextField();
        jnum2 = new javax.swing.JTextField();
        jsomar = new javax.swing.JButton();
        jsubtrair = new javax.swing.JButton();
        jdividir = new javax.swing.JButton();
        jporcent = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlimpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jresultado = new javax.swing.JTextField();
        jmult = new javax.swing.JButton();
        jcontinua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));
        setFocusCycleRoot(false);

        lblnum1.setText("Numero 1:");

        jLabel1.setText("Numero 2:");

        jnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnum1ActionPerformed(evt);
            }
        });

        jnum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnum2ActionPerformed(evt);
            }
        });

        jsomar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jsomar.setText("+");
        jsomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsomarActionPerformed(evt);
            }
        });

        jsubtrair.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jsubtrair.setText("-");
        jsubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubtrairActionPerformed(evt);
            }
        });

        jdividir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jdividir.setText("/");
        jdividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdividirActionPerformed(evt);
            }
        });

        jporcent.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jporcent.setText("%");
        jporcent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jporcentActionPerformed(evt);
            }
        });

        jLabel2.setText("Escolha qual operação será executada:");

        jlimpar.setText("CLEAR");
        jlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlimparActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 102));
        jLabel3.setText("Calculadora");

        jLabel4.setText("Digite os numeros que desejar:");

        jLabel5.setText("Resultado:");

        jresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresultadoActionPerformed(evt);
            }
        });

        jmult.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jmult.setText("X");
        jmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmultActionPerformed(evt);
            }
        });

        jcontinua.setText("LAST OP.");
        jcontinua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcontinuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblnum1)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jnum1)
                                        .addComponent(jnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jsomar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jlimpar)
                                        .addGap(27, 27, 27)
                                        .addComponent(jcontinua))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jsubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jdividir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jporcent, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jmult, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnum1)
                    .addComponent(jnum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jnum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsomar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdividir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jporcent, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmult, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlimpar)
                    .addComponent(jcontinua))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnum1ActionPerformed

    private void jnum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnum2ActionPerformed

    private void jsubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubtrairActionPerformed
        // TODO add your handling code here:
         // here the number 1 and 2 receive the real number and only real
      // the method parseDouble converts what is in parentheses to a string
      // in this case i converted jnum1 for text 
      num1 = Double.parseDouble(jnum1.getText()); 
      num2 = Double.parseDouble(jnum2.getText());
      
      resultado = num1 - num2;
     
      //jresultado receive value from variable results converted from real to string 
      jresultado.setText(Double.toString(resultado));
        
    }//GEN-LAST:event_jsubtrairActionPerformed

    private void jlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlimparActionPerformed
        // TODO add your handling code here:
        jnum1.setText("");
        jnum2.setText("");
        jresultado.setText("");

    }//GEN-LAST:event_jlimparActionPerformed

    private void jresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jresultadoActionPerformed

    private void jsomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsomarActionPerformed
      // here the number 1 and 2 receive the real number and only real
      // the method parseDouble converts what is in parentheses to a string
      // in this case i converted jnum1 for text 
      num1 = Double.parseDouble(jnum1.getText()); 
      num2 = Double.parseDouble(jnum2.getText());
      
      resultado = num1 + num2;
     
      //jresultado receive value from variable results converted from real to string 
      jresultado.setText(Double.toString(resultado));
    }//GEN-LAST:event_jsomarActionPerformed

    private void jdividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdividirActionPerformed
        // TODO add your handling code here:
         // here the number 1 and 2 receive the real number and only real
      // the method parseDouble converts what is in parentheses to a string
      // in this case i converted jnum1 for text 
      num1 = Double.parseDouble(jnum1.getText()); 
      num2 = Double.parseDouble(jnum2.getText());
      
      resultado = num1 / num2;
     
      //jresultado receive value from variable results converted from real to string 
      jresultado.setText(Double.toString(resultado));
    }//GEN-LAST:event_jdividirActionPerformed

    private void jporcentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jporcentActionPerformed
        // TODO add your handling code here:
         // here the number 1 and 2 receive the real number and only real
      // the method parseDouble converts what is in parentheses to a string
      // in this case i converted jnum1 for text 
      num1 = Double.parseDouble(jnum1.getText()); 
      num2 = Double.parseDouble(jnum2.getText());
      
      resultado = (num1 / 100) * num2;
     
      //jresultado receive value from variable results converted from real to string 
      jresultado.setText(Double.toString(resultado));
    }//GEN-LAST:event_jporcentActionPerformed

    private void jmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmultActionPerformed
      // here the number 1 and 2 receive the real number and only real
      // the method parseDouble converts what is in parentheses to a string
      // in this case i converted jnum1 for text 
      num1 = Double.parseDouble(jnum1.getText()); 
      num2 = Double.parseDouble(jnum2.getText());
      
      resultado = num1 * num2;
     
      //jresultado receive value from variable results converted from real to string 
      jresultado.setText(Double.toString(resultado));
    }//GEN-LAST:event_jmultActionPerformed

    private void jcontinuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcontinuaActionPerformed
        // TODO add your handling code here:
        jnum1.setText(Double.toString(resultado));
        jnum2.setText("");
        jresultado.setText("");       
    }//GEN-LAST:event_jcontinuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceSimples().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jcontinua;
    private javax.swing.JButton jdividir;
    private javax.swing.JButton jlimpar;
    private javax.swing.JButton jmult;
    private javax.swing.JTextField jnum1;
    private javax.swing.JTextField jnum2;
    private javax.swing.JButton jporcent;
    private javax.swing.JTextField jresultado;
    private javax.swing.JButton jsomar;
    private javax.swing.JButton jsubtrair;
    private javax.swing.JLabel lblnum1;
    // End of variables declaration//GEN-END:variables
}
